language: python
python:
  - "3.6"
  - "3.7"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow_cpu-2.3.0-cp36-cp36m-manylinux2010_x86_64.whl; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow_cpu-2.3.0-cp37-cp37m-manylinux2010_x86_64.whll; fi
  - python setup.py -q install
  - pip install pylint pydocstyle

script:
  - python -m unittest discover tests -p "*_test.py"
  - pylint word2vec
  - pydocstyle word2vec
