language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip install tensorflow>=2.0.0
  - pip install setuptools>=41.0.0
  - python setup.py -q install
  - pip install pylint pydocstyle

script:
  - python -m unittest discover tests -p "*_test.py"
  - pylint word2vec
  - pydocstyle word2vec
