language: python
python:
  - "3.5"
  - "3.6"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-2.0.0-cp35-cp35m-manylinux2010_x86_64.whl; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-2.0.0-cp36-cp36m-manylinux2010_x86_64.whl; fi
  - python setup.py -q install
  - pip install pylint pydocstyle

script:
  - python -m unittest discover tests -p "*_test.py"
  - pylint word2vec
  - pydocstyle word2vec
