version: 1
formatters:
  brief:
    format: '%(levelname)s - %(message)s'
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
loggers:
  nonce2vec.main:
    level: INFO
    handlers: [console]
  nonce2vec.utils:
    level: INFO
    handlers: [console]
  nonce2vec.models.word2vec:
    level: INFO
    handlers: [console]
